백엔드 체스방 생성 풀리퀘
junseokho/cptm.net pull request #4
Opened 2024-10-08 06:24 UTC by jongyoung3

- 체스방 생성, 참여, 참여가능 방 목록 조회 기능 구현
- DB를 MySQL로 변경 -> 하지만 각자 MySQL의 DB를 따로 파야 할 것 같음.
- DB 공유 방법 필요
- 방 나가기, 방 제거 기능 추가 필요
- 방 생성 시 DTO에서 보내는 정보를 id ->username로 변경 고려 필요

2024-10-08 06:40 UTC, sony-string commented on src/main/java/com/example/chessdotnet/config/DataInitializer.java
어떤 문제인지 간략하게 알려주면 도와줄 수 있을지도?

2024-10-08 06:43 UTC, jongyoung3 commented on src/main/java/com/example/chessdotnet/config/DataInitializer.java
이거 실행하면 초기 값으로 유저 데이터 2명이 셋팅되는데, 나중에 지우고 다시 셋팅하면 id가 다시 1,2가 되는게 아니라 3,4 로 시작하는 문제임.
- 이건 내일 얘기 해보자

2024-10-08 06:47 UTC, sony-string requested changes
리뷰 적어놓은 것들 확인해주삼 (아무때나 시간날때)

2024-10-08 06:47 UTC, sony-string commented on src/main/java/com/example/chessdotnet/config/SecurityConfig.java
32라인에서 /api 로 시작하는 모든 요청은 모든 사용자에게 허용하면 안되나요

2024-10-08 06:47 UTC, sony-string commented on src/main/java/com/example/chessdotnet/dto/JoinRoomRequest.java
방 관련 Dto 는 한 파일에 묶는게 편할듯

2024-10-08 07:02 UTC, jongyoung3 commented on src/main/java/com/example/chessdotnet/config/SecurityConfig.java
모든 사용자에게 허용으로 되있지않음?

2024-10-09 06:37 UTC, sony-string approved these changes
수정사항보류

2024-10-09 06:38 UTC, merged