Origin/dev 브랜치 생성 및 RoomService 수정
junseokho/cptm.net pull request #7
Opened 2024-10-10 09:53 UTC by jongyoung3

- RoomService 의 방 나가기, 방 삭제 기능 조건 수정
- orgin/dev 브랜치 생성

2024-10-10 14:25 UTC, sony-string requested changes

2024-10-10 14:25 UTC, sony-string commented on build.gradle
(수업때 말했다시피) 프론트/백엔드 동시에 실행하는 빌드 기능을 안넣을 생각이라 build.gradle 변경 취소해주세요

2024-10-11 01:00 UTC, sony-string approved these changes

2024-10-11 01:11 UTC, jongyoung3 commented on build.gradle
수정 완료

2024-10-12 07:23 UTC, sony-string commented on build.gradle
approve 하였음

2024-10-12 07:27 UTC, jongyoung3 commented on build.gradle
병합할게

2024-10-12 07:28 UTC, merged